language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bustercodes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bustercodes/docker-react npm run test
